### PR TITLE
Wrapper function for get_gender, changes question to set expt.gender

### PR DESCRIPTION
**Pull request by Comeani**
Want to change the question the experimenter is asked while setting up expt from the biological sex of the participant to their height, as VTL strongly correlates with body height. 

Corresponding change to new run_EXPTNAME_expt scripts:
``if ~isfield(expt,'gender'), expt.gender = get_height; end``

### CODE REVIEW

**Review by cwnaber — APPROVED** [review]
Tested with SSW and it works well.

**Comment by cwnaber** [comment]
Is any other testing needed before this gets merged?

**Comment by cwnaber** [comment]
> Was the testing you did on an experiment running machine? If not I'll see if Lana can sanity check that and then I'll merge it.

No I just tested on my personal computer

**Comment by lhantzsch** [comment]
Tested it on Burnham, and is functioning as expected.

**Comment by lhantzsch** [comment]
When this gets merged, can you also update the run_modelExpt_expt.m to use this function?

**Comment by cwnaber** [comment]
Good call Lana, updated modelExpt on this branch so it'll merge alongside `get_height`.

**Pull request merged**
